/**
 * Renders the service worker (ADR-013) for a given list of built files.
 * Kept separate from the build script so it can be unit tested.
 *
 * - install: precache every built file (the app is small; all of it
 *   together is the "works offline for a session" promise);
 * - activate: drop caches from older builds;
 * - fetch: cache-first for precached files, network-first with an offline
 *   fallback to index.html for page navigations. Nothing else is cached,
 *   and nothing is ever sent anywhere — progress stays in IndexedDB.
 */
export function renderServiceWorker(files: readonly string[], version: string): string {
  const urls = ['./', ...files.map((file) => `./${file}`)]
  return `// Generated by scripts/build-sw.ts — do not edit.
const CACHE = 'latvian-trainer-${version}'
const PRECACHE = ${JSON.stringify(urls, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // Refresh the cached app shell only from a good response for the app
          // root itself — never let a 404 page replace it.
          const root = new URL('./', self.location).pathname
          const path = new URL(request.url).pathname
          if (response.ok && (path === root || path === root + 'index.html')) {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put('./', copy))
          }
          return response
        })
        .catch(() => caches.match('./')),
    )
    return
  }

  event.respondWith(caches.match(request).then((cached) => cached ?? fetch(request)))
})
`
}
